name: native_ads_example
description: Demonstrates how to use the native_ads plugin.
publish_to: 'none'
version: 0.4.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  native_ads:
    path: ../
 
flutter:
 
  uses-material-design: true
 